### ISSUE TITLE
$ctx->addheader in EOH callback?

### ISSUE THREAD

**Issue by randolf** [avar/sendmail-pmilter#9]
Documentation states that `addheader` is only callable in the EOM callback.  Is there a reason why we can't use this in the EOH callback?  If not, it would be nice to be able to do this so that adding headers that are based on existing headers can be programmed into the EOH callback.

Thanks.

**Comment by gjskha** [comment]
To your point about calling `$ctx->addheader` in the EOH callback I can't say anything,  but I recall that `$ctx->setpriv` and `$ctx->getpriv` contains a private scalar variable available in all callbacks. Since `header_callback` is called on every header, maybe data could be concatenated to the private scalar variable depending on what you find in a given header.  Perhaps the example scripts at milter.org in the Internet Archive from 2015 or earlier, or documentation from ancient sendmail tarballs can help you out. YMMV.

**Comment by randolf** [comment]
Thanks for your prompt answer; it's all working just fine, including with the approach you suggested.

I was merely wondering if I could do this in the EOH callback instead of the EOM callback -- apparently it's not possible because the milter protocol itself doesn't support this (based on some documentation I discovered since raising this issue).

**Comment by randolf** [comment]
Thanks for your prompt answer; it's all working just fine, including with the approach you suggested.

I was merely wondering if I could do this in the EOH callback instead of the EOM callback -- apparently it's not possible because the milter protocol itself doesn't support this (based on some documentation I discovered since raising this issue).

**Comment by randolf** [comment]
Thanks for your prompt answer; it's all working just fine, including with the approach you suggested.

I was merely wondering if I could do this in the EOH callback instead of the EOM callback -- apparently it's not possible because the milter protocol itself doesn't support this (based on some documentation I discovered since raising this issue).
